apiVersion: v1
kind: Service
metadata:
  name: gs-websocket-service
spec:
  selector:
    app: gs-websocket
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30544

  type: NodePort
  