apiVersion: apps/v1
kind: Deployment
metadata:
  name: gs-websocket
  labels:
    role: gs-websocket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gs-websocket
  template:
    metadata:
      labels:
        app: gs-websocket
    spec:
      containers:
        - name: gs-websocket
          image: kchabin/spring-guide:1.3
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
  